### ISSUE TITLE
why

### ISSUE THREAD

**Issue by imgrizzly** [bengland2/smallfile#2]
[root@localhost smallfile-master]# python smallfile_cli.py --top /nfs/test/ --operation create --host-set 172.16.149.42 --network-sync-dir /tmp/smallfile-master/test/
smallfile version 3.0
                           hosts in test : ['172.16.149.42']
                   top test directory(s) : ['/nfs/test']
                               operation : create
                            files/thread : 200
                                 threads : 2
           record size (KB, 0 = maximum) : 0
                          file size (KB) : 64
                  file size distribution : fixed
                           files per dir : 100
                            dirs per dir : 10
              threads share directories? : N
                         filename prefix : 
                         filename suffix : 
             hash file number into dir.? : N
                     fsync after modify? : N
          pause between files (microsec) : 0
                    finish all requests? : Y
                              stonewall? : Y
                 measure response times? : N
                            verify read? : Y
                                verbose? : False
                          log to stderr? : False
                           ext.attr.size : 0
                          ext.attr.count : 0
               permute host directories? : N
                remote program directory : /tmp/smallfile-master
               network thread sync. dir. : /tmp/smallfile-master/test/
Exception seen in thread 00 host 172.16.149.42 (tail /var/tmp/invoke_logs-00.log) 
Exception seen in thread 01 host 172.16.149.42 (tail /var/tmp/invoke_logs-01.log) 
Traceback (most recent call last):
  File "/tmp/smallfile-master/smallfile_remote.py", line 48, in <module>
    run_workload()
  File "/tmp/smallfile-master/smallfile_remote.py", line 39, in run_workload
    return multi_thread_workload.run_multi_thread_workload(params)
  File "/tmp/smallfile-master/multi_thread_workload.py", line 107, in run_multi_thread_workload
    % startup_timeout)
Exception: threads did not reach starting gate within 11 sec
thread ssh-thread:172.16.149.42:256:ssh -x -o StrictHostKeyChecking=no  172.16.149.42 "python /tmp/smallfile-master/smallfile_remote.py --network-sync-dir /tmp/smallfile-master/test/  --as-host 172.16.149.42" has died
Traceback (most recent call last):
  File "smallfile_cli.py", line 280, in <module>
    run_workload()
  File "smallfile_cli.py", line 270, in run_workload
    return run_multi_host_workload(params)
  File "smallfile_cli.py", line 182, in run_multi_host_workload
    'within %d seconds' % host_timeout)
Exception: hosts did not reach starting gate within 17 seconds

**Comment by bengland2** [comment]
look in /var/tmp/invoke_logs*log  on the target system and you'll probably see what went wrong.

**Comment by imgrizzly** [comment]
[root@centos smallfile-master]# tail /var/tmp/invoke_logs-01.log
01 2016-01-27 18:02:21,494 - INFO - do_workload:  opname=create iterations=200 top_dirs=['/nfs/test'] src_dirs=['/nfs/test/file_srcdir/172.16.149.42/thrd_01'] dest_dirs=['/nfs/test/file_dstdir/172.16.149.42/thrd_01'] network_dir=/tmp/smallfile-master/test/ shared=False record_sz_kb=0 total_sz_kb=64 filesize_distr=-1 files_per_dir=100 dirs_per_dir=10 dirs_on_demand=False xattr_size=0 xattr_count=0 starting_gate=/tmp/smallfile-master/test/starting_gate.tmp prefix= suffix= hash_to_dir=False fsync=False stonewall=True files_between_checks=20 verify_read=True incompressible=False finish_all_rq=True rsp_times=False tid=01 loglevel=20 filenum=0 filenum_final=0 rq=0 rq_final=0 start=None end=None elapsed=0 host=172.16.149.42 status=1 abort=False log_to_stderr=False verbose=False
01 2016-01-27 18:02:21,496 - ERROR - thread 01 saw abort flag
[root@centos smallfile-master]# tail /var/tmp/invoke_logs-00.log
00 2016-01-27 18:02:21,494 - INFO - do_workload:  opname=create iterations=200 top_dirs=['/nfs/test'] src_dirs=['/nfs/test/file_srcdir/172.16.149.42/thrd_00'] dest_dirs=['/nfs/test/file_dstdir/172.16.149.42/thrd_00'] network_dir=/tmp/smallfile-master/test/ shared=False record_sz_kb=0 total_sz_kb=64 filesize_distr=-1 files_per_dir=100 dirs_per_dir=10 dirs_on_demand=False xattr_size=0 xattr_count=0 starting_gate=/tmp/smallfile-master/test/starting_gate.tmp prefix= suffix= hash_to_dir=False fsync=False stonewall=True files_between_checks=20 verify_read=True incompressible=False finish_all_rq=True rsp_times=False tid=00 loglevel=20 filenum=0 filenum_final=0 rq=0 rq_final=0 start=None end=None elapsed=0 host=172.16.149.42 status=1 abort=False log_to_stderr=False verbose=False
00 2016-01-27 18:02:21,496 - ERROR - thread 00 saw abort flag

**Comment by imgrizzly** [comment]
I'm sorry, I was wrong, network-sync-dir and top two parameters engage in counter. You can now properly run. In addition, ask what time multi-host mode can be used for windows it?

**Comment by bengland2** [comment]
I'm not totally understanding your questions, but it sounds like you got it running.  Multi-host mode works for Windows, I've tested it (not recently) but you have to start up a launch_smf_host.py on each Windows box to listen for work to do.  Hopefully docs cover this?  If not let me know and I'll fix docs.
