### ISSUE TITLE
AttributeError: smf_test_params instance has no attribute 'recalculate_timeouts'

### ISSUE THREAD

**Issue by shreekarSS** [bengland2/smallfile#7]
While trying to do some IOs on mount point, got this-->>
 sudo python smallfile_cli.py --operation create --threads 8   --file-size 1024 --files 2048 --top /mnt/mpoint/
                                 version : 3.1
                           hosts in test : None
                   top test directory(s) : ['/mnt/cephfs']
                               operation : create
                            files/thread : 2048
                                 threads : 8
           record size (KB, 0 = maximum) : 0
                          file size (KB) : 1024
                  file size distribution : fixed
                           files per dir : 100
                            dirs per dir : 10
              threads share directories? : N
                         filename prefix : 
                         filename suffix : 
             hash file number into dir.? : N
                     fsync after modify? : N
          pause between files (microsec) : 0
                    finish all requests? : Y
                              stonewall? : Y
                 measure response times? : N
                            verify read? : Y
                                verbose? : False
                          log to stderr? : False
                           ext.attr.size : 0
                          ext.attr.count : 0
Traceback (most recent call last):
  File "smallfile_cli.py", line 279, in <module>
    run_workload()
  File "smallfile_cli.py", line 264, in run_workload
    params = parse.parse()
  File "/home/cephuser/smallfile/parse.py", line 280, in parse
    test_params.recalculate_timeouts()
AttributeError: smf_test_params instance has no attribute 'recalculate_timeouts'

**Comment by bengland2** [comment]
Shreekar, sorry about that, I'll try to get that fixed ASAP.  was checking in some fixes to another problem and I lost track of dependencies.   I think smallfile needs stable version tags to make it easy for people to grab the latest stable version.

**Comment by bengland2** [comment]
@shreekarSS a fix is checked into github now.  Could you try this one and let me know if it doesn't work?  I ran regtest.sh and also did some other tests to verify that it was calculating timeouts better now.  If you use --format-json your-test.json, you'll be able to see the timeout parameters used and you can adjust them using -min-dirs-per-sec parameter so that you can make timeout longer if directory creation in your filesystem is expensive.
-bene

**Comment by shreekarSS** [comment]
Thanks @bengland2 , it's working

**Comment by bengland2** [comment]
thx for letting me know
