### ISSUE TITLE
smallfile requires the --top directory to be mounted on driver

### ISSUE THREAD

**Issue by wilkins11** [bengland2/smallfile#9]
This is new behavior (version : 3.1) that doesn't seem correct. I've never had to have the target directory mounted on the driver used to run smallfile tests on remote clients.

```
# ./smallfile_cli.py --host-set "gprfc001" --response-times N --same-dir N --stonewall N --top /mnt/cephfs/smf/ --network-sync-dir /smfnfs/sync/ --threads 1 --files 256 --files-per-dir 1000 --file-size 4 --file-size-distribution exponential --operation create

ERROR: you must ensure that shared directory /mnt/cephfs/smf is accessible from this host and every remote host in test
```

on baremetal RHEL 7.5 (3.10.0-862)

**Comment by bengland2** [comment]
@wilkins11 reproduced, found root cause, fix is on the way

**Comment by bengland2** [comment]
[this commit ](https://github.com/bengland2/smallfile/commit/6dbffa9190f869be5616115f1894d94b2be7f433 )should fix it, @wilkins11

**Comment by bengland2** [comment]
closing due to lack of feedback
